name: sgi
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: '4.0.0'
  flutter_slidable: "^0.6.0"
  async_loader: ^0.1.2
  path_provider: ^2.0.2
  http: ^0.13.3
  charcode: ^1.1.2
  shared_preferences: "2.0.6"
  advance_pdf_viewer: any
  pin_code_fields: ^7.2.0

  cupertino_icons: ^1.0.2
  sqflite: any
  email_validator: '^1.0.6'
  
  google_fonts: ^2.0.0
  expandable: ^5.0.1
  money2: ^2.2.1
  intl: ^0.17.0
  idb_sqflite: ^1.0.0
  sembast_web: ^2.0.0+2
  native_pdf_view: ^4.1.0
  native_pdf_renderer: ^3.1.0
  syncfusion_flutter_pdfviewer: ^19.2.47-beta
  circular_profile_avatar: ^0.1.5
  cached_network_image: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/face.png
    - assets/images/logo_asa.png
    - assets/images/marca.png
    - assets/images/CSC1.png
    - assets/images/CSC2.png
    - assets/images/logo_colorida.png
    - assets/images/logo_branca.png
    - assets/images/verify.png
    - assets/images/email.png
    - assets/images/otp.gif
    - assets/images/LogoCircular_Asa.png
    - assets/images/LogoCircular_MaceioDistribuidora.png
    - assets/images/LogoCircular_MsLog.png
    - assets/images/LogoCircular_Cose.png
    - assets/images/LogoCircular_Gentileza.png
    - assets/images/email_sent2.jpg